### PR TITLE
Changed web superheading to regular weight

### PR DESCRIPTION
**Pull request by nataliafitzgerald**

### CODE REVIEW

**Comment by Scotchester** [comment]
Reviewed this in person :+1:

**Comment by jimmynotjim** [comment]
Needs to be released as a breaking change or there needs to be a bugfix to point the existing `.superheader` to `.superheading`

**Comment by Scotchester** [comment]
@jimmynotjim Crap, sorry for overlooking that. I'll submit a PR to add the pointer.

**Comment by jimmynotjim** [comment]
Thanks :facepunch: 

Sidenote, that emoji is `facepunch`? It's just `punch` in Slack

**Comment by Scotchester** [comment]
Slack has tons of aliases for the "standard" names. `facepunch` works in Slack, as does `fistbump`

**Comment by Scotchester** [comment]
Oops... I accidentally pushed direct to upstream due to a git remote mixup. @jimmynotjim, can you look at this commit and give the thumbs up? https://github.com/cfpb/cf-core/commit/172d44f9d3b59611e7f0e00304ad0df67ec7922c

Since we hadn't made the 1.3.1 release yet, I figured we could roll it into that.

**Comment by jimmynotjim** [comment]
Looks good. @cfarm or @KimberlyMunoz want to sign off as well?

**Comment by jimmynotjim** [comment]
@Scotchester lets go ahead and package this into a release.

**Comment by Scotchester** [comment]
@jimmynotjim Donezo. Thanks.

**Pull request merged**
