### PR TITLE
Accessibility testing

### PR DESCRIPTION
**Pull request by contolini**
Adds automated pa11y test to be run by Travis CI.
## Additions
- Adds `npm test` script.
- Adds config file for Travis CI.
- Adds Travis CI badge to readme.
## Testing
- Pull down changes.
- `npm install`
- `npm test`
## Review
- @anselmbradford

### CODE REVIEW

**Comment by anselmbradford** [comment]
Getting `PhantomJS not found in PATH` error after `npm install` and `npm test` on this one, which is weird because I see phantomjs installed in the log.

`pa11y localhost:8080/demo -s WCAG2AA` gives same error.

**Comment by anselmbradford** [comment]
Threw out node_modules and ran `npm install` and `npm test` and it worked now ¯_(ツ)_/¯

**Comment by anselmbradford** [comment]
Pa11y tests are failing though, as expected?

**Comment by Scotchester** [comment]
I think @contolini was singularly focused on getting the tests running, not trying to get them to pass.

**Comment by contolini** [comment]
Correct, a few components have their pa11y tests failing which is something we should look into after these accessibility-testing branches are merged in.

**Pull request merged**
