### PR TITLE
Changing color for default links to make visited links 508 compliant

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
As I was about to change something in another repo, I was getting a pa11y error because the visited links don't have enough contrast against white. I've changed the colors to make them 508 compliant.

Let me know what the plan is for the next release. Thanks!
## Review
- @Scotchester 
- @jimmynotjim

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1: I think this can be a patch to help get all our other tests passing, but I'll defer to @Scotchester b/c he understands the surge work better.

**Comment by Scotchester** [comment]
I think we should revisit the default calculations for the other states at some point in the future, but :+1: as a quick fix for all the failing tests.

**Comment by Scotchester** [comment]
Let's go ahead and bump the version and make a new release so it'll stop failing other components' tests if they bring in the new version.

**Comment by Scotchester** [comment]
To make my request explicit: @KimberlyMunoz, please bump the version in `bower.json` and add something to the change log.

**Comment by KimberlyMunoz** [comment]
Would this be a patch release?

**Comment by Scotchester** [comment]
Yeah

**Comment by KimberlyMunoz** [comment]
Changelog and bower updated.

**Comment by Scotchester** [comment]
:+1:

**Comment by Scotchester** [comment]
Please tag and release.

**Pull request merged**
