### PR TITLE
Fix to override browser stylesheets for TH

### PR DESCRIPTION
**Pull request by mistergone**
This is a small PR that addresses some browser stylesheet defaults which cause TH elements to be bold and center-aligned by default.

Short description explaining the high-level reason for the pull request
## Additions
- LESS for TH elements, and TH elements in a TBODY (to set the font to normal weight)
## Review
- @Scotchester - I figure a quick look from you is all this requires...
## Special Thanks

Thanks to @Scotchester for opinions on the best way to do this!
## Animated GIF

Aggressive browser stylesheets make me feel like:
headdesk-o

### CODE REVIEW

**Comment by Scotchester** [comment]
Code looks good. Please update the version number in `bower.json`, add an entry to the change log, and we're good to go.

**Comment by mistergone** [comment]
Version and CHANGELOG have been updated! :rocket: :octopus:

**Comment by Scotchester** [comment]
Got merge conflicts now, sorry!

**Comment by mistergone** [comment]
Merge conflicts repaired, so this should be ready to go again.

**Comment by Scotchester** [comment]
:metal: Rockin' :guitar:

Thanks!

**Pull request merged**
