### PR TITLE
fieldset legend

### PR DESCRIPTION
**Pull request by cfarm**
adds default legend element style for new design manual standards.

needed for cf-forms: https://github.com/cfpb/cf-forms/pull/38

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Unrelated, but are you all going to add styles for fieldsets too? `normalize.css` adds a terrible off-brand border I overwrite anytime I want to use them and it'd be nice to have that go away.

**Comment by KimberlyMunoz** [comment]
Nevermind, I see the design manual is going with borders by default. https://github.com/cfpb/cf-forms/pull/38

**Comment by jimmynotjim** [comment]
:+1:

**Comment by Scotchester** [comment]
:+1:

**Comment by Scotchester** [comment]
Before merging, @cfarm could you create an "Unreleased" section in the change log and note what you've changed here? That'll make it easier for writing the release notes when we do a big release after all these DM-related updates. Thanks.

**Comment by cfarm** [comment]
@Scotchester do you need me to do that for each component?

@KimberlyMunoz I thought that fieldset style was part of CF! Ha. I'll ask @sonnakim if I should create one based on the existing form styles. That will be a future PR, though.

**Comment by sonnakim** [comment]
@cfarm @KimberlyMunoz Agreed, no fieldset borders! The fieldset style should probably be what the Flapjack team has defined, with a grey background and fieldset label. <a href="http://beta.consumerfinance.gov/sub-pages/submit-a-request/">The submit a request form</a> shows the grey background and I have an illustrator file with fieldset labels and a few stacked fieldsets that I can share.

**Comment by Scotchester** [comment]
@cfarm I think it's most important for cf-core, because lots of different people are touching it right now. Alternatively, if you want to just go ahead and bump the version and make a release, that'd be fine, too.

**Comment by cfarm** [comment]
@Scotchester I tagged the latest commit here and I'll make a release when it's merged.

**Comment by Scotchester** [comment]
Need an update to the version in `bower.json` and a note in `CHANGELOG.md`, please!

**Comment by jimmynotjim** [comment]
@cfarm there's been a few more releases in the time being, you'll need to delete the local tag, pull in `gh-pages`, updated and commit the `bower.json` and `CHANGELOG.md` and push that up to this branch. I've started waiting till PRs are merged with `gh-pages` to tag because I've had this same thing happen before.

**Comment by Scotchester** [comment]
Obsolete.

**Pull request closed without merging**
