### PR TITLE
Responsive headers

### PR DESCRIPTION
**Pull request by virginiacc**
- Make h1-h3 responsive.
- Add screen size variables.

### CODE REVIEW

**Comment by Scotchester** [comment]
Looks pretty good! One question: Did the `h1` not need any bottom margin adjustments?

**Comment by virginiacc** [comment]
The `h1` was the only header whose bottom margin had already been approximated to 30px, so it didn't need to be updated.

**Comment by Scotchester** [comment]
Ah! Right you are. Sorry :)

**Comment by himedlooff** [comment]
Thanks!

**Comment by virginiacc** [comment]
Thank you!

**Pull request merged**
